# Thomas Chromium - Self-Hosted Build Configuration
# Uses your Linux machine (thomas-lenovo) to build Linux + cross-compile Windows

env:
  CHROMIUM_VERSION: "131.0.6778.139"
  DEPOT_TOOLS_UPDATE: "0"

# ============================================================================
# Linux Build (Native)
# ============================================================================
linux_build_task:
  name: "Linux Build"
  timeout_in: 480m  # 8 hours max
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /cache/depot_tools:$PATH
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget lsb-release sudo pkg-config file
    - apt-get install -y build-essential ninja-build clang lld
    - apt-get install -y libgtk-3-dev libglib2.0-dev libnss3-dev libcups2-dev libxss-dev libasound2-dev libxkbcommon-dev
  
  setup_depot_tools_script:
    - |
      if [ ! -d "/cache/depot_tools/.git" ]; then
        echo "Cloning depot_tools..."
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /cache/depot_tools
      fi
    - cd /cache/depot_tools
    - |
      # Only update depot_tools if it hasn't been updated in the last 24 hours
      if [ ! -f "/cache/depot_tools/.last_update" ] || [ $(find /cache/depot_tools/.last_update -mmin +1440 2>/dev/null) ]; then
        echo "Updating depot_tools..."
        ./update_depot_tools || true
        touch /cache/depot_tools/.last_update
      else
        echo "depot_tools is up to date (updated within 24h)"
      fi
  
  fetch_chromium_script:
    - mkdir -p /cache/chromium
    - cd /cache/chromium
    - |
      # Check if Chromium source exists
      if [ ! -d "src/.git" ]; then
        echo "Fetching Chromium source for the first time..."
        fetch --nohooks --no-history chromium
        cd src
        git checkout $CHROMIUM_VERSION || git checkout main
        gclient sync --nohooks -D
      else
        cd src
        # Check current version
        CURRENT_VERSION=$(git describe --tags --always 2>/dev/null || git rev-parse HEAD)
        echo "Current version: $CURRENT_VERSION"
        echo "Target version: $CHROMIUM_VERSION"
        
        # Only sync if version doesn't match
        if echo "$CURRENT_VERSION" | grep -q "$CHROMIUM_VERSION"; then
          echo "✅ Already on correct version, skipping fetch!"
        else
          echo "Version mismatch, updating..."
          git fetch origin || true
          git checkout $CHROMIUM_VERSION || git checkout main
          gclient sync --nohooks -D
        fi
      fi
  
  install_build_deps_script:
    - cd /cache/chromium/src
    - |
      # Only run install-build-deps if not already done
      if [ ! -f "/cache/.build_deps_installed" ]; then
        echo "Installing Chromium build dependencies..."
        ./build/install-build-deps.sh --no-prompt || true
        touch /cache/.build_deps_installed
      else
        echo "✅ Build dependencies already installed, skipping!"
      fi
    - echo "Running gclient runhooks..."
    - gclient runhooks
  
  apply_patches_script:
    - cd /cache/chromium/src
    - echo "Applying Thomas Chromium patches..."
    - cp -r $CIRRUS_WORKING_DIR/patches /tmp/patches || true
    - |
      for patch in /tmp/patches/branding/*.patch; do
        if [ -f "$patch" ]; then
          echo "Applying $patch"
          git apply "$patch" 2>/dev/null || echo "Patch already applied or doesn't match"
        fi
      done
  
  configure_script:
    - cd /cache/chromium/src
    - mkdir -p out/Release
    - |
      cat > out/Release/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      blink_symbol_level = 0
      is_component_build = false
      proprietary_codecs = true
      ffmpeg_branding = "Chrome"
      use_sysroot = true
      EOF
    - echo "Running gn gen..."
    - gn gen out/Release
  
  build_script:
    - cd /cache/chromium/src
    - echo "Starting Chromium build with 10 parallel jobs..."
    - autoninja -C out/Release chrome -j10
  
  package_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src
    - tar -czvf $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-linux-x64.tar.gz -C out/Release chrome chrome_sandbox *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"

# ============================================================================
# Windows Build (Cross-compiled from Linux)
# ============================================================================
windows_cross_build_task:
  name: "Windows Build (Cross-compile)"
  timeout_in: 480m
  depends_on:
    - "Linux Build"  # Reuse the cached source
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /cache/depot_tools:$PATH
    DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget pkg-config file zip
    - apt-get install -y build-essential ninja-build clang lld
  
  configure_windows_script:
    - cd /cache/chromium/src
    - mkdir -p out/Release-win
    - |
      cat > out/Release-win/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_os = "win"
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      is_component_build = false
      EOF
    - gn gen out/Release-win
  
  build_windows_script:
    - cd /cache/chromium/src
    - autoninja -C out/Release-win chrome -j10
  
  package_windows_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src/out/Release-win
    - zip -r $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-win-x64.zip chrome.exe *.dll *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"
