# Thomas Chromium - Self-Hosted Build Configuration
# Uses your Linux machine (thomas-lenovo) to build Linux + cross-compile Windows

env:
  CHROMIUM_VERSION: "131.0.6778.139"
  DEPOT_TOOLS_UPDATE: "0"

# ============================================================================
# Linux Build (Native)
# ============================================================================
linux_build_task:
  name: "Linux Build"
  timeout_in: 480m  # 8 hours max
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /cache/depot_tools:$PATH
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget lsb-release sudo pkg-config file
    - apt-get install -y build-essential ninja-build clang lld
    - apt-get install -y libgtk-3-dev libglib2.0-dev libnss3-dev libcups2-dev libxss-dev libasound2-dev libxkbcommon-dev
  
  setup_depot_tools_script:
    - |
      if [ ! -d "/cache/depot_tools/.git" ]; then
        echo "Cloning depot_tools..."
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /cache/depot_tools
      fi
    - cd /cache/depot_tools
    - echo "Bootstrapping depot_tools..."
    - ./update_depot_tools || true
    - echo "depot_tools ready at /cache/depot_tools"
  
  fetch_chromium_script:
    - mkdir -p /cache/chromium
    - cd /cache/chromium
    - |
      if [ ! -d "src/.git" ]; then
        echo "Fetching Chromium source (this takes a while)..."
        fetch --nohooks --no-history chromium
      else
        echo "Chromium source already exists, updating..."
      fi
    - cd src
    - git fetch origin || true
    - git checkout $CHROMIUM_VERSION || git checkout main || true
    - gclient sync --nohooks -D
  
  install_build_deps_script:
    - cd /cache/chromium/src
    - echo "Installing Chromium build dependencies..."
    - ./build/install-build-deps.sh --no-prompt || true
    - echo "Running gclient runhooks..."
    - gclient runhooks
  
  apply_patches_script:
    - cd /cache/chromium/src
    - echo "Applying Thomas Chromium patches..."
    - cp -r $CIRRUS_WORKING_DIR/patches /tmp/patches || true
    - |
      for patch in /tmp/patches/branding/*.patch; do
        if [ -f "$patch" ]; then
          echo "Applying $patch"
          git apply "$patch" || echo "Patch may already be applied or doesn't match"
        fi
      done
  
  configure_script:
    - cd /cache/chromium/src
    - mkdir -p out/Release
    - |
      cat > out/Release/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      blink_symbol_level = 0
      is_component_build = false
      proprietary_codecs = true
      ffmpeg_branding = "Chrome"
      use_sysroot = true
      EOF
    - echo "Running gn gen..."
    - gn gen out/Release
  
  build_script:
    - cd /cache/chromium/src
    - echo "Starting Chromium build with 10 parallel jobs..."
    - autoninja -C out/Release chrome -j10
  
  package_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src
    - tar -czvf $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-linux-x64.tar.gz -C out/Release chrome chrome_sandbox *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"

# ============================================================================
# Windows Build (Cross-compiled from Linux)
# ============================================================================
windows_cross_build_task:
  name: "Windows Build (Cross-compile)"
  timeout_in: 480m
  depends_on:
    - "Linux Build"  # Reuse the cached source
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /cache/depot_tools:$PATH
    DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget pkg-config file
    - apt-get install -y build-essential ninja-build clang lld
    - apt-get install -y wine64 || true
  
  configure_windows_script:
    - cd /cache/chromium/src
    - mkdir -p out/Release-win
    - |
      cat > out/Release-win/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_os = "win"
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      is_component_build = false
      EOF
    - gn gen out/Release-win
  
  build_windows_script:
    - cd /cache/chromium/src
    - autoninja -C out/Release-win chrome -j10
  
  package_windows_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src/out/Release-win
    - apt-get install -y zip
    - zip -r $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-win-x64.zip chrome.exe *.dll *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"
