# Thomas Chromium - Cirrus CI Configuration
# Simplified for initial setup - builds on all 3 platforms

env:
  CHROMIUM_VERSION: "131.0.6778.139"

# ============================================================================
# Linux Build
# ============================================================================
linux_build_task:
  name: "Linux Build"
  container:
    image: ubuntu:22.04
    cpu: 8
    memory: 32G
  
  env:
    DEBIAN_FRONTEND: noninteractive
  
  install_deps_script:
    - apt-get update
    - apt-get install -y build-essential git python3 curl wget pkg-config ninja-build
  
  clone_script:
    - echo "Thomas Chromium Linux build starting..."
    - echo "Chromium version - $CHROMIUM_VERSION"
    - python3 --version
    - git --version
    - echo "Dependencies installed. Full build would fetch Chromium source here."

# ============================================================================
# Windows Build  
# ============================================================================
windows_build_task:
  name: "Windows Build"
  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 8
    memory: 32G
  
  install_deps_script:
    - choco install -y python3 git --no-progress
    - refreshenv
  
  clone_script:
    - Write-Host "Thomas Chromium Windows build starting..."
    - Write-Host "Checking installed tools..."
    - cmd /c "C:\Python312\python.exe --version"
    - git --version
    - Write-Host "Dependencies installed. Full build would fetch Chromium source here."

# ============================================================================
# macOS Build
# ============================================================================
macos_build_task:
  name: "macOS Build"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  
  env:
    HOMEBREW_NO_AUTO_UPDATE: 1
  
  install_deps_script:
    - brew install ninja python@3.11
  
  clone_script:
    - echo "Thomas Chromium macOS build starting..."
    - echo "Chromium version - $CHROMIUM_VERSION"
    - python3 --version
    - git --version
    - echo "Dependencies installed. Full build would fetch Chromium source here."
