# Thomas Chromium - Self-Hosted Build Configuration
# Uses your Linux machine (thomas-lenovo) to build Linux + cross-compile Windows

env:
  CHROMIUM_VERSION: "131.0.6778.139"
  DEPOT_TOOLS_UPDATE: "0"

# ============================================================================
# Linux Build (Native)
# ============================================================================
linux_build_task:
  name: "Linux Build"
  timeout_in: 480m  # 8 hours max
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget lsb-release sudo pkg-config file xz-utils
    - apt-get install -y build-essential ninja-build clang lld
    - apt-get install -y libgtk-3-dev libglib2.0-dev libnss3-dev libcups2-dev libxss-dev libasound2-dev libxkbcommon-dev
  
  setup_depot_tools_script:
    - |
      if [ ! -d "/cache/depot_tools/.git" ]; then
        echo "Cloning depot_tools..."
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /cache/depot_tools
      fi
    - export PATH="/cache/depot_tools:$PATH"
    - cd /cache/depot_tools
    - |
      # Bootstrap depot_tools - this creates the python3_bin_reldir.txt
      echo "Bootstrapping depot_tools..."
      python3 -c "import sys; print(sys.version)"
      ./cipd --version || ./ensure_bootstrap
      echo "depot_tools ready"
  
  fetch_chromium_script:
    - export PATH="/cache/depot_tools:$PATH"
    - mkdir -p /cache/chromium
    - cd /cache/chromium
    - |
      if [ ! -d "src/.git" ]; then
        echo "Fetching Chromium source for the first time..."
        fetch --nohooks --no-history chromium
      fi
    - cd /cache/chromium/src
    - |
      # Get current commit
      CURRENT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "none")
      echo "Current commit: $CURRENT_COMMIT"
      echo "Target version: $CHROMIUM_VERSION"
      
      # Check if we need to update
      # Store a marker file with the last successful version
      if [ -f "/cache/.chromium_version" ] && [ "$(cat /cache/.chromium_version)" = "$CHROMIUM_VERSION" ]; then
        echo "✅ Already on correct version ($CHROMIUM_VERSION), skipping sync!"
      else
        echo "Updating to version $CHROMIUM_VERSION..."
        
        # Fetch tags explicitly
        git fetch --tags origin || true
        
        # Try to checkout the version tag
        if git checkout "$CHROMIUM_VERSION" 2>/dev/null; then
          echo "Checked out tag $CHROMIUM_VERSION"
        elif git checkout "tags/$CHROMIUM_VERSION" 2>/dev/null; then
          echo "Checked out tags/$CHROMIUM_VERSION"  
        else
          echo "Tag $CHROMIUM_VERSION not found, staying on current branch"
        fi
        
        # Sync dependencies
        gclient sync --nohooks -D
        
        # Mark version as synced
        echo "$CHROMIUM_VERSION" > /cache/.chromium_version
        echo "✅ Sync complete, version marked as $CHROMIUM_VERSION"
      fi

  
  install_build_deps_script:
    - export PATH="/cache/depot_tools:$PATH"
    - cd /cache/chromium/src
    - |
      if [ ! -f "/cache/.build_deps_installed" ]; then
        echo "Installing Chromium build dependencies..."
        ./build/install-build-deps.sh --no-prompt || true
        touch /cache/.build_deps_installed
      else
        echo "✅ Build dependencies already installed, skipping!"
      fi
    - echo "Running gclient runhooks..."
    - gclient runhooks
  
  apply_patches_script:
    - cd /cache/chromium/src
    - echo "Applying Thomas Chromium patches..."
    - cp -r $CIRRUS_WORKING_DIR/patches /tmp/patches || true
    - |
      for patch in /tmp/patches/branding/*.patch; do
        if [ -f "$patch" ]; then
          echo "Applying $patch"
          git apply "$patch" 2>/dev/null || echo "Patch already applied or doesn't match"
        fi
      done
  
  configure_script:
    - export PATH="/cache/depot_tools:$PATH"
    - |
      # Ensure depot_tools is bootstrapped before using gn
      cd /cache/depot_tools
      ./cipd --version 2>/dev/null || ./ensure_bootstrap || true
    - cd /cache/chromium/src
    - mkdir -p out/Release
    - |
      cat > out/Release/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      blink_symbol_level = 0
      is_component_build = false
      proprietary_codecs = true
      ffmpeg_branding = "Chrome"
      use_sysroot = true
      EOF
    - echo "Running gn gen..."
    - /cache/depot_tools/gn gen out/Release
  
  build_script:
    - export PATH="/cache/depot_tools:$PATH"
    - cd /cache/chromium/src
    - echo "Starting Chromium build with 10 parallel jobs..."
    - /cache/depot_tools/autoninja -C out/Release chrome -j10
  
  package_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src
    - tar -czvf $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-linux-x64.tar.gz -C out/Release chrome chrome_sandbox *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"

# ============================================================================
# Windows Build (Cross-compiled from Linux)
# ============================================================================
windows_cross_build_task:
  name: "Windows Build (Cross-compile)"
  timeout_in: 480m
  depends_on:
    - "Linux Build"
  
  persistent_worker:
    labels:
      os: linux
    isolation:
      container:
        image: ubuntu:22.04
        cpu: 10
        memory: 20G
        volumes:
          - /tmp/chromium-cache:/cache
  
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
  
  install_deps_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip curl wget pkg-config file zip xz-utils
    - apt-get install -y build-essential ninja-build clang lld
  
  configure_windows_script:
    - export PATH="/cache/depot_tools:$PATH"
    - cd /cache/chromium/src
    - mkdir -p out/Release-win
    - |
      cat > out/Release-win/args.gn << 'EOF'
      is_official_build = true
      is_debug = false
      target_os = "win"
      target_cpu = "x64"
      enable_nacl = false
      symbol_level = 0
      is_component_build = false
      EOF
    - /cache/depot_tools/gn gen out/Release-win
  
  build_windows_script:
    - export PATH="/cache/depot_tools:$PATH"
    - cd /cache/chromium/src
    - /cache/depot_tools/autoninja -C out/Release-win chrome -j10
  
  package_windows_script:
    - mkdir -p $CIRRUS_WORKING_DIR/artifacts
    - cd /cache/chromium/src/out/Release-win
    - zip -r $CIRRUS_WORKING_DIR/artifacts/thomas-chromium-win-x64.zip chrome.exe *.dll *.pak *.bin locales resources || true
  
  artifacts:
    path: "artifacts/*"
